# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "weekly"
